version: "3.7"

services:
        bindserver:
                build:
                        context: BindServer
                        dockerfile: Dockerfile
                ports:
                        - 53:53
                volumes:
                        - ./BindServer/config:/etc/bind 
                links:
                        - "webgoat:webgoat"
                        - "apache:apache"
                        - "debian:debian"
                        - "curler:curler"
                networks:
                        - HIR

        apache:
                build:
                        context: Apache
                        dockerfile: Dockerfile
                ports:
                        - 80:80
                        - 443:443
                volumes:
                        - ./Apache/config:/etc/apache2 
                links:
                        - "webgoat:webgoat"
                        - "badstore:badstore"
                networks:
                        - HIR

        debian:
                build:
                        context: Debian
                        dockerfile: Dockerfile
                links:
                        - "apache:apache"
                networks:
                        - HIR

        curler:
                image: debian/latest
                links:
                        - "apache:apache"
                volumes:
                        - ./Curler/config:~/
                networks:
                        - HIR

        webgoat:
                image: webgoat/webgoat-8.0
                networks:
                        - HIR

        badstore:
                image: jvhoof/badstore-docker
                networks:
                        - HIR

networks:
        HIR:
                driver: bridge
                
