version: "3"

services:
        bindserver:
                build:
                        context: bindserver
                        dockerfile: Dockerfile
                ports:
                        
