version: "3.7"

services:
        bindserver:
                build:
                        context: BindServer
                        dockerfile: Dockerfile
                volumes:
                        - ./BindServer/config:/etc/bind 
                links:
                        - "webgoat:webgoat"
                        - "web:web"
                        - "curler:curler"
                networks:
                        HIR:
                            ipv4_address: "10.8.10.5"
                dns: "10.8.10.5"
                expose: ["53"]
                command: ["named", "-c", "/etc/bind/named.conf", "-g", "-u","root"]
                stdin_open: true
                tty: true
        web:
                build:
                        context: Apache
                        dockerfile: Dockerfile
                
                working_dir: /var/www/html
                volumes:
                        - ./Apache/config:/etc/apache2
                        - ./Apache/pages:/var/www/
                links:
                        - "webgoat:webgoat"
                        - "badstore:badstore"
                networks:
                        HIR:
                            ipv4_address: "10.8.10.3"
                expose: ["80","443"]
                dns: "10.8.10.5"
                command: ["apache2ctl", "-D", "FOREGROUND"]
                stdin_open: true
                tty: true
 


        curler:
                image: debian:latest
                links:
                        - "web:web"
                volumes:
                        - ./Curler/config:/root/
                networks:
                        - HIR
                dns: "10.8.10.5"

        webgoat:
                image: webgoat/webgoat-8.0

        badstore:
                image: jvhoof/badstore-docker

networks:
        HIR:
            driver: bridge
            ipam:
                 config:
                     - subnet: "10.8.10.0/24"
