version: "3.7"

services:
        bindserver:
                build:
                        context: BindServer
                        dockerfile: Dockerfile
                expose:
                        - 53
                volumes:
                        - ./BindServer/config:/etc/bind 
                links:
                        - "webgoat:webgoat"
                        - "web:web"
                        - "curler:curler"
                networks:
                        - HIR
                stdin_open: true
                tty: true
        web:
                build:
                        context: Apache
                        dockerfile: Dockerfile
                
                working_dir: /var/www/html
                expose:
                        - 80
                        - 443
                volumes:
                        - ./Apache/config:/etc/apache2 
                links:
                        - "webgoat:webgoat"
                        - "badstore:badstore"
                networks:
                        - HIR
                stdin_open: true
                tty: true
 


        curler:
                image: debian:latest
                links:
                        - "web:web"
                volumes:
                        - ./Curler/config:/root/
                networks:
                        - HIR

        webgoat:
                image: webgoat/webgoat-8.0

        badstore:
                image: jvhoof/badstore-docker

        wordpress:


networks:
        HIR:
            driver: bridge
            ipam:
                 driver: default
                 config:
                     - subnet: "10.8.10.0/24"
