version: "3.7"

services:

##--------------------------------
#       Vulnerable Services
##--------------------------------

        bindserver:
                hostname: "Bind"
                container_name: "Bind"
                build:
                        context: BindServer
                        dockerfile: Dockerfile
                volumes:
                        - ./BindServer/config:/etc/bind 
                links:
                        - "webgoat:webgoat"
                        - "web:web"
                        - "curler:curler"
                networks:
                        HIR:
                            ipv4_address: "10.8.10.5"
                dns: "10.8.10.5"
                expose: ["53"]
                command: ["named", "-c", "/etc/bind/named.conf", "-g", "-u","root"]
                stdin_open: true
                tty: true
        web:
                hostname: "Apache"
                container_name: "Apache"
                build:
                        context: Apache
                        dockerfile: Dockerfile
                
                working_dir: /var/www/html
                volumes:
                        - ./Apache/config:/etc/apache2
                        - ./Apache/pages:/var/www/
                        - ./Apache/certs:/etc/certs/
                links:
                        - "webgoat:webgoat"
                        - "badstore:badstore"
                networks:
                        HIR:
                            ipv4_address: "10.8.10.3"
                expose: ["80","443"]
                dns: "10.8.10.5"
                command: ["apache2ctl", "-D", "FOREGROUND"]
                stdin_open: true
                tty: true

 
        curler:
                hostname: "Curler"
                container_name: "Curler"
                image: debian:latest
                links:
                        - "web:web"
                volumes:
                        - ./Curler/config:/root/
                networks:
                        - HIR
                dns: "10.8.10.5"

        webgoat:
                hostname: "WebGoat"
                container_name: "WebGoat"
                image: szsecurity/webgoat
                expose: ["80"] 
                networks:
                        HIR:
                            ipv4_address: "10.8.10.21"
 
        badstore:
                hostname: "BaadStore"
                container_name: "BadStore"
                image: jvhoof/badstore-docker
                networks:
                        HIR:
                            ipv4_address: "10.8.10.22"
 
        dvwa:
                hostname: "DamnVulnaberaleWebApp"
                container_name: "DamnVulnaberaleWebApp"
                image: vulnerables/web-dvwa
                networks:
                        HIR:
                            ipv4_address: "10.8.10.23"
 
        mutillidae:
                hostname: "Mutillidate"
                container_name: "Mutillidate"
                image: szsecurity/mutillidae
                networks:
                        HIR:
                            ipv4_address: "10.8.10.24"
 
        bwap:
                hostname: "bWapp"
                container_name: "bWapp"
                image: raesene/bwapp
                networks:
                        HIR:
                            ipv4_address: "10.8.10.25"
 
        jucieshop:
                hostname: "JuiceShop"
                container_name: "JuiceShop"
                image: bkimminich/juice-shop
                networks:
                        - HIR
                networks:
                        HIR:
                           ipv4_address: "10.8.10.26"
 
        nessus:
                hostname: "Nessus"
                container_name: "Nessus"
                image: sometheycallme/docker-nessus
                expose: [8834]
                networks:
                        HIR:
                            ipv4_address: "10.8.10.10"
                dns: "10.8.10.5"
        
        wordpress:
                hostname: "Wordpress"
                container_name: "Wordpress"
                image: wordpress
                restart: always
                expose: [80, 443]
                depends_on: 
                        - db
                environment:
                        WORDPRESS_DB_HOST: db:3306
                        WORDPRESS_DB_USER: user
                        WORDPRESS_DB_PASSWORD: user
                        WORDPRESS_DB_NAME: wordpress
                networks:
                        HIR:
                            ipv4_address: "10.8.10.27"
                links:
                        - "db:db"

        db:
                hostname: "Mysql"
                container_name: "Mysql"
                image: mysql:5.7
                restart: always
                environment:
                        MYSQL_DATABASE: wordpress
                        MYSQL_USER: user
                        MYSQL_PASSWORD: user
                        MYSQL_RANDOM_ROOT_PASSWORD: '1'
                networks:
                        HIR:
                            ipv4_address: "10.8.10.9"


networks:
        HIR:
            driver: bridge
            ipam:
                 config:
                         - subnet: "10.8.10.0/24"
